apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: upgrade-insecure-requests
  namespace: elpai-openschema
spec:
  headers:
    customResponseHeaders:
      Content-Security-Policy: "upgrade-insecure-requests"