apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multichat-gradio-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: multichat-gradio=cr.elpai.org/elpai-openschema/multichat-gradio
    argocd-image-updater.argoproj.io/multichat-gradio.update-strategy: semver
    argocd-image-updater.argoproj.io/multichat-gradio.allow-tags: 'regexp:^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$'
  finalizers: []
spec:
  destination:
    namespace: elpai-openschema-prod
    server: https://kubernetes.default.svc
  source:
    path: manifests/overlays/prod
    repoURL: https://github.com/ELPAI-OpenSchema/multichat-gradio.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: false
    syncOptions:
      - CreateNamespace=true
