apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multichat-gradio-stg
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: multichat-gradio=cr.elpai.org/elpai-openschema/multichat-gradio:stg
    argocd-image-updater.argoproj.io/multichat-gradio.update-strategy: newest-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elpai-openschema-stg
    server: https://kubernetes.default.svc
  source:
    path: manifests/overlays/stg
    repoURL: https://github.com/ELPAI-OpenSchema/multichat-gradio.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
